#!/bin/bash

# A little script to create a new site in nginx.
#
# @author JohnG <john.gieselmann@gmail.com>
#
# @param str $1 The new domain name including the TLD.
#
# @param str $2 The optional site type [html | laravel] If blank, it defaults
# to html.

# make sure we at least have the new domain name
if [[ -z $1 ]] ; then
    printf "%s\n\n" "Usage: newsite <domain_name.tld> <site-type>"
    printf "%s\n" "Ex: newsite jam.com laravel"
    printf "%s\n" " - jam.com will be inserted as the nginx server_name"
    printf "%s\n" " - site type [html | laravel] will determine the default config file used. If none is defined, html is used."
    exit
else
    site="$1"
fi

# assign the document root automatically
sites="/srv/www"
doc_root="$sites/$site/public_html"

# set the default config file
if [[ -z $2 ]] ; then
    site_type="html"
else
    site_type="$2"
fi

# copy the newsite template virtual host to this new site
sites_available="/etc/nginx/sites-available"
new_conf="$sites_available/$site"
cp $sites_available/default.$site_type $new_conf

# replace the values in the new file
sed -i "/^##/d" $new_conf
sed -i "s/<%url%>/$site/g" $new_conf

# create the root directory for the site
if [[ ! -d $doc_root ]] ; then
    mkdir -p $doc_root
    printf "%s\n" "Creating root directory: $doc_root"
else
    printf "%s\n" "Root directory exists: $doc_root"
fi

# create the log directory for the site
log_dir="/srv/www/$site/logs"
if [[ ! -d $log_dir ]] ; then
    mkdir $log_dir
    printf "%s\n" "Creating log directory: $log_dir"
else
    printf "%s\n" "Log directory exists: $log_dir"
fi

# enable the new site by symlinking to sites-enabled
nginx_ensite $site

# check if we should reload nginx
reload_prompt="Reload nginx?"
read -p "$reload_prompt [y/N]" reload_response

if [[ -z "$reload_response" ]] ; then
    printf "%s\n" "Not reloading nginx"
else
    if [[ "$reload_response" = "y" || "$reload_response" = "Y" ]] ; then
        nginx_out=$(service nginx reload)
        printf "%s\n" "$nginx_out"
    fi
fi

# reminder message to add the DNS records for this site
printf "\n%s\n" "Donezo. Don't forget to create the DNS records for this new site."

# donezo
exit
